<referenceBlock name="footer">
    <block class="Magento\Framework\View\Element\Html\Links" name="footer_links_account" after="footer_links">
        <arguments>
            <argument name="css_class" xsi:type="string">footer_links</argument>
            <block class="Magento\Framework\View\Element\Html\Link\Current" name="my-account-link">
                <arguments>
                    <argument name="label" xsi:type="string">My account</argument>
                    <argument name="path" xsi:type="string">customer/account</argument>
                    </arguments>
            </block>
            <block class="Magento\Framework\View\Element\Html\Link\Current" name="my-cart-link">
                <arguments>
                    <argument name="label" xsi:type="string">My cart</argument>
                    <argument name="path" xsi:type="string">checkout/cart</argument>
                    <arguments>
            </block>
        </arguments>
    </block>
</referenceBlock>