<?php
namespace Khoa\District\Block\Admin\Customer;

class Edit extends \Magento\Framework\View\Element\Template
{

    protected $_urlBuilder;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        array $data = []
    )
    {
        $this->_urlBuilder = $context->getUrlBuilder();
        parent::__construct($context, $data);
    }

    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
    public function getUrlController()
    {
        return $this->getUrl('district/customer/index');
    }
}